/* Package Code.gs for Cloudflare, unchanged.

     node build.cjs       (run by `npm run dev` and `npm run deploy`)

   Code.gs is written for Google Apps Script: one big script whose functions
   all see each other. Cloudflare runs JavaScript modules and does not allow
   code to be built from text while it runs, so the script is wrapped, as it
   is, in one function that returns what the server needs. The Google
   services it calls are handed in as stand-ins (see src/google.js), and its
   records go to the Durable Object's database (src/sqlstore.js) instead of
   hidden sheets.

   The output, src/app.gen.js, is made fresh every time and never edited:
   Code.gs stays the one copy of the app's rules, for Google and Cloudflare
   alike. */
const fs = require('fs'), path = require('path');

const src = fs.readFileSync(path.join(__dirname, '..', 'Code.gs'), 'utf8');
const build = (src.match(/var SERVER_BUILD = '([^']+)'/) || [])[1] || '?';

// Everything Code.gs reaches for outside itself.
const GOOGLE = ['Utilities', 'ContentService', 'LockService', 'Session', 'UrlFetchApp', 'SpreadsheetApp',
                'DriveApp', 'ScriptApp', 'Logger', 'PropertiesService', 'CacheService'];
// What the server calls in it.
const EXPORTS = ['handle', 'purgeOrphans_', 'backfillRegionRates_', 'bumpRev_', 'cacheClear_', 'getRev_',
                 'sheetMemoClear_', 'setSeasonContext_', 'flushStockMoves_',
                 // (and for the tests, which start from the same sample tour as test/mini.js)
                 'ensureReady', 'markDirtyAll_', 'doCreateRegion', 'dbUpdate_', 'activeSeasonId_', 'objectsOf_',
                 // (and for the spreadsheet bridge: what Google learned, written back)
                 'setMeta_', 'getMeta_', 'dbInsert_', 'dbHas_', 'activitySheet_'];

const out = `/* GENERATED by build.js from Code.gs (${build}) — do not edit; edit Code.gs. */
export const CODE_BUILD = ${JSON.stringify(build)};
export function makeApp(G) {
  var ${GOOGLE.map(n => n + ' = G.' + n).join(', ')};
// ----- Code.gs -----
${src}
// ----- end of Code.gs -----
  STORE_ = G.store; KV_ = G.kv;          // the database, not the hidden sheets
  REPORTS_HERE_ = G.reportsHere !== false;   // spreadsheets stay with Google
  return { ${EXPORTS.map(n => n + ': ' + n).join(', ')}, BOOKS: BOOKS, WAREHOUSE: WAREHOUSE, QUIET_MS: QUIET_MS };
}
`;
fs.mkdirSync(path.join(__dirname, 'src'), { recursive: true });
fs.writeFileSync(path.join(__dirname, 'src', 'app.gen.js'), out);
console.log('Built src/app.gen.js from Code.gs ' + build);
